# yaml-language-server: schema=https://json.schemastore.org/github-action

name: Build
on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: denoland/setup-deno@v1
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: deno task build
    - uses: actions/upload-artifact@v3
      with:
        name: license
        path: license
        if-no-files-found: error
